language: node_js

node_js:
- '10'

before_script:
- npm i

script:
- npm run lint

deploy:
  provider: heroku
  api_key:
    secure: r8EdaoJsmWXDaeZqpjJsDvj8zKGGUieoWVQ7ZcNSsyRJe4UEX9OO0fePQWNF8n1NWACKfWmS3Xmtuwc76WztSLRZnD4dzXHxi0HAJej/IgAp/9XVEC7zuBmkHhCvgoTAzpVX6VyQkcaVxMQEPkT/QU6jrajtdRp/MWJRZhrwdb96AU1yYapzLJa/Ga2me1XG84unuOQG5VXNye52gpX6AHjQdJf+B6OXfLDsK4HdV3hSPPOXvAVJnw32yb9CeCtudQK9ggJXU+IFtlQW1wYAcNYaAaaJ5c9MhjxOlsvld7x7reNaKTzS2XSp3t3dWacoApJY8J/vkaJytlmIWBNhbCDb7aIhhcn2Xzjp4v/pkq0Uc+RggdnarzI/2MRKApJmZIDjyp9jbGMBw6mm9sjLLI3Rllc9a0lx359kklhlblcKVsDhkYgNkHvTsTGEH+xMhvM5SiUvWYpr0Bw5TtCJ5MGYYoQPLd9Dun1b1i+dwbaRIKD/wsLo2L+aAvM3QOd6WfYMIgH7j3SydUvtoPHi2ZUyFWrZYCMvLiMkTpCabs7wgJCGuhSvL/VynNn7v0651d6AJER45pmFEASVT8sk7CDBtNvaCXoprqOK9vh7T4LCrihlpRvDpHNyrcF1E7mRBjPyAGicsPLkMYbyaXLIWq5cKL4caZiN2aXlYeVK21E=
  app: kinc-shinshu-hubot
