language: node_js

node_js:
  - '10'

before_script:
  - npm i

script:
  - npm run lint

deploy:
  provider: heroku
  api_key:
    secure: LQXVImTL3NNtEudES5bogIM6nybE0ErRJfFOxWcU6X/bc1WHPT687rKYw+ixYH19xrxrnasQZLFMren+dq3J3uWDoRCjQhJdhSv3Q+wiNs/ILfH4+Y/xRp23Qowj0jWnTIxCUaoLxiZIGi7fY34AdsRYX7TBinktRqDm4L1wq2LIDzPK4bau/abCfu4ZnXtSXjPat87LaOFXlj4myE91YyNYxC/W7P0JbWKAKOVgj04vdZQ/EkKDB6FfOj2+xNjlHWljZ/IdsNlTPe28VXkfozC8/ZgGMT0uvT3SCCNM/3EDTSicdD78o2+E1bCgOO/HLdiiG/17jhJT1koDzjxnFt1MNzAz0D8tdRyNXMR8icoCByGCG8ENt69DZIkgdFAZb2NwnaIQAtGERFmXIa2cmOe0u4gZeBL8xBioO/ejVkF3fDZYxQ/qEcU0qKqTFaZ7W8FG92JYbHwE6SsXcd6TB3URB2CNpNFMswLfbP7ufym2u6VJ2d8FcEJuDNm9VJrFHacbKzlbbrXVWYlIxAMh95asgJ5cerdcWigsc0EAtbU5pzShgWukhLTw1ZNU3B2N8VjQdXsOXgzND9CMuBBsx1MnA0OYwj2lg+25Tkkdg/a/lYwTGMW1yih7Uh+h2DwCq5BBVJjNGhEpF4e897wtu8WsQ5EjtcIPiy1TC/y2s5o=
